# JustAFK Configuration
tagmessages: true

# AFK-related options
autokick: true
hideawayplayers: true
broadcastawaymsg: true
movementcheckfreq: 180 #seconds
kicktime: 900 #seconds
kickreason: '&cYou were inactive for too long!'
kickwhileinvehicle: true